Update README.md
viam-modules/viam-ufactory-xarm pull request #5
Opened 2024-12-11 22:47 UTC by JessamyT

2024-12-11 22:57 UTC, nfranczak requested changes

2024-12-11 22:57 UTC, nfranczak commented on README.md
> +This is a [Viam module](https://docs.viam.com/how-tos/create-module/) for [UFactory's](https://www.ufactory.cc/) X-ARM 6 and X-ARM 7 collaborative arms.
nit: lite6 is also included in this

2024-12-11 22:57 UTC, nfranczak commented on README.md
> +Navigate to the **CONFIGURE** tab of your machine’s page in [the Viam app](https://app.viam.com/). Click the **+** icon next to your machine part in the left-hand menu and select **Component**. Selec
nit: lite6 should also be included

2024-12-11 23:13 UTC, JessamyT commented on README.md
> +This is a [Viam module](https://docs.viam.com/how-tos/create-module/) for [UFactory's](https://www.ufactory.cc/) X-ARM 6 and X-ARM 7 collaborative arms.
Oops yep yep
```suggestion
This is a [Viam module](https://docs.viam.com/how-tos/create-module/) for [UFactory's](https://www.ufactory.cc/) X-ARM 6, X-ARM 7, and LITE 6 collaborative arms.
```

2024-12-11 23:14 UTC, JessamyT commented on README.md
> +Navigate to the **CONFIGURE** tab of your machine’s page in [the Viam app](https://app.viam.com/). Click the **+** icon next to your machine part in the left-hand menu and select **Component**. Selec
```suggestion
Navigate to the **CONFIGURE** tab of your machine’s page in [the Viam app](https://app.viam.com/). Click the **+** icon next to your machine part in the left-hand menu and select **Component**. Select the `arm` type, then search for and select the `arm / ufactory:xArm6`, `arm / ufactory:xArm7`, or `arm / ufactory:lite6` model, depending on your hardware model. Click **Add module**, then enter a name or use the suggested name for your arm and click **Create**.
```

2024-12-12 17:33 UTC, nfranczak approved these changes
Thank you for handling this! 🚀

2024-12-17 17:36 UTC, merged